#!/bin/bash
# PharmTeX Linux bash script, part of the PharmTeX platform.
# Copyright (C) 2018 Christian Hove Rasmussen (contact@pharmtex.org).
# This program is free software: You can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program (see file named LICENSE). If not, see <https://www.gnu.org/licenses/>.

# Set main path for PharmTeX
LDIR="$HOME/pharmtex"; export LDIR

# Get job name and mode
NAME=$(basename "$1")
EXT="${NAME##*.}"
NAME="${NAME%.*}"
MODE="$2"

# If no options set, prompt user
if [ -z "$NAME" ] && [ -z "$MODE" ]; then
	read -p 'File to edit = ' NAME
	MODE=gui
fi

# Choose batch mode if no mode set
if [ -z "$MODE" ]; then
	MODE=batch
fi

# Temporarily change paths
OLDPATH="$PATH"
PATH="$LDIR/bin:$LDIR/java/bin:$LDIR/perl/bin:$LDIR/texlive/bin/x86_64-linux:$LDIR/texmaker:$PATH"; export PATH
MANPATH="$LDIR/texlive/texmf-dist/doc/man:$MANPATH"; export MANPATH
INFOPATH="$LDIR/texlive/texmf-dist/doc/info:$INFOPATH"; export INFOPATH

# Exit if script is run to set path only
if [ "$MODE" == "path" ]; then 
	exit;
fi

# Load MiKTeX Tool if gui mode
if [ "$MODE" == "gui" ]; then
	texmaker "$NAME.tex"
else
	perl runlatex.pl "$NAME" "$MODE"
fi

# Clean up
if [ -e jabref.xml ]; then
	mv jabref.xml "$LDIR/jabref/jabref.xml"
fi
if [ -e dodel.txt ]; then
	rm dodel.txt "$NAME.pdf" 
fi
PATH="$OLDPATH"; export PATH
